### ISSUE TITLE
migrate pulp db step throws below error w/ sat-clone 1.1.0.rc1

### ISSUE THREAD

**Issue by sghai** [RedHatSatellite/satellite-clone#189]
```console
TASK [satellite-clone : Restore new mongo data] ********************************
Wednesday 26 April 2017  04:56:53 -0400 (0:00:00.033)       0:48:37.569 ******* 
skipping: [SAT_SERVER]

TASK [satellite-clone : migrate pulp db] ***************************************
Wednesday 26 April 2017  04:56:54 -0400 (0:00:00.027)       0:48:37.596 ******* 
fatal: [SAT_SERVER]: FAILED! => {"changed": true, "cmd": ["sudo", "-u", "apache", "pulp-manage-db"], "delta": "0:06:19.588021", "end": "2017-04-26 05:03:14.594398", "failed": true, "rc": 70, "start": "2017-04-26 04:56:55.006377", "stderr": "Mongo database for connection is version 2.4.9\nLoading content types.\nLoading type descriptors [nodes.json, iso_support.json, rpm_support.json, docker.json, puppet.json]\nParsing type descriptors\nValidating type descriptor syntactic integrity\nValidating type descriptor semantic integrity\nUpdating the database with types [repository, node, iso, distribution, drpm, erratum, package_group, package_category, package_environment, rpm, srpm, yum_repo_metadata_file, docker_image, puppet_module]\nFound the following type definitions that were not present in the update collection [docker_blob, docker_tag, docker_manifest]\nException updating unit key for type [erratum]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 119, in update_database\n    _update_unit_key(type_def)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 321, in _update_unit_key\n    _update_indexes(type_def, True)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 312, in _update_indexes\n    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 916, in ensure_index\n    return self.create_index(key_or_list, cache_for, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 823, in create_index\n    **self._get_wc_override())\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 357, in insert\n    continue_on_error, self.__uuid_subtype), safe)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 920, in _send_message\n    rv = self.__check_response_to_last_error(response)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 861, in __check_response_to_last_error\n    raise DuplicateKeyError(details[\"err\"], details[\"code\"])\nDuplicateKeyError: E11000 duplicate key error index: pulp_database.units_erratum.$id_1  dup key: { : null }\nException updating unit key for type [package_group]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 119, in update_database\n    _update_unit_key(type_def)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 321, in _update_unit_key\n    _update_indexes(type_def, True)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 312, in _update_indexes\n    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 916, in ensure_index\n    return self.create_index(key_or_list, cache_for, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 823, in create_index\n    **self._get_wc_override())\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 357, in insert\n    continue_on_error, self.__uuid_subtype), safe)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 920, in _send_message\n    rv = self.__check_response_to_last_error(response)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 861, in __check_response_to_last_error\n    raise DuplicateKeyError(details[\"err\"], details[\"code\"])\nDuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_group.$id_1_repo_id_1  dup key: { : null, : \"esi-Development-RHEL5Server_x86_64-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_5_Server_RPMs_x86_64_5Server\" }\nException updating unit key for type [package_category]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 119, in update_database\n    _update_unit_key(type_def)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 321, in _update_unit_key\n    _update_indexes(type_def, True)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 312, in _update_indexes\n    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 916, in ensure_index\n    return self.create_index(key_or_list, cache_for, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 823, in create_index\n    **self._get_wc_override())\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 357, in insert\n    continue_on_error, self.__uuid_subtype), safe)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 920, in _send_message\n    rv = self.__check_response_to_last_error(response)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 861, in __check_response_to_last_error\n    raise DuplicateKeyError(details[\"err\"], details[\"code\"])\nDuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_category.$id_1_repo_id_1  dup key: { : null, : \"esi-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_5_Server_RPMs_i386_5Server\" }\nException updating unit key for type [package_environment]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 119, in update_database\n    _update_unit_key(type_def)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 321, in _update_unit_key\n    _update_indexes(type_def, True)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 312, in _update_indexes\n    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 916, in ensure_index\n    return self.create_index(key_or_list, cache_for, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/connection.py\", line 167, in retry\n    return method(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 823, in create_index\n    **self._get_wc_override())\n  File \"/usr/lib64/python2.7/site-packages/pymongo/collection.py\", line 357, in insert\n    continue_on_error, self.__uuid_subtype), safe)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 920, in _send_message\n    rv = self.__check_response_to_last_error(response)\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 861, in __check_response_to_last_error\n    raise DuplicateKeyError(details[\"err\"], details[\"code\"])\nDuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_environment.$id_1_repo_id_1  dup key: { : null, : \"esi-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_3\" }\nUpdateFailed [erratum, package_group, package_category, package_environment]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/manage.py\", line 125, in main\n    return _auto_manage_db(options)\n  File \"/usr/lib/python2.7/site-packages/pulp/server/db/manage.py\", line 150, in _auto_manage_db\n    old_content_types = load_content_types(dry_run=options.dry_run)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py\", line 417, in load_content_types\n    _load_type_definitions(descriptors)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py\", line 484, in _load_type_definitions\n    database.update_database(definitions)\n  File \"/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py\", line 133, in update_database\n    raise UpdateFailed(error_defs)\nUpdateFailed: UpdateFailed [erratum, package_group, package_category, package_environment]", "stdout": "", "stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}

cmd: sudo -u apache pulp-manage-db

start: 2017-04-26 04:56:55.006377

end: 2017-04-26 05:03:14.594398

delta: 0:06:19.588021

stderr: Mongo database for connection is version 2.4.9
Loading content types.
Loading type descriptors [nodes.json, iso_support.json, rpm_support.json, docker.json, puppet.json]
Parsing type descriptors
Validating type descriptor syntactic integrity
Validating type descriptor semantic integrity
Updating the database with types [repository, node, iso, distribution, drpm, erratum, package_group, package_category, package_environment, rpm, srpm, yum_repo_metadata_file, docker_image, puppet_module]
Found the following type definitions that were not present in the update collection [docker_blob, docker_tag, docker_manifest]
Exception updating unit key for type [erratum]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 119, in update_database
    _update_unit_key(type_def)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 321, in _update_unit_key
    _update_indexes(type_def, True)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 312, in _update_indexes
    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 916, in ensure_index
    return self.create_index(key_or_list, cache_for, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 823, in create_index
    **self._get_wc_override())
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 357, in insert
    continue_on_error, self.__uuid_subtype), safe)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 861, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], details["code"])
DuplicateKeyError: E11000 duplicate key error index: pulp_database.units_erratum.$id_1  dup key: { : null }
Exception updating unit key for type [package_group]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 119, in update_database
    _update_unit_key(type_def)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 321, in _update_unit_key
    _update_indexes(type_def, True)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 312, in _update_indexes
    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 916, in ensure_index
    return self.create_index(key_or_list, cache_for, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 823, in create_index
    **self._get_wc_override())
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 357, in insert
    continue_on_error, self.__uuid_subtype), safe)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 861, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], details["code"])
DuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_group.$id_1_repo_id_1  dup key: { : null, : "esi-Development-RHEL5Server_x86_64-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_5_Server_RPMs_x86_64_5Server" }
Exception updating unit key for type [package_category]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 119, in update_database
    _update_unit_key(type_def)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 321, in _update_unit_key
    _update_indexes(type_def, True)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 312, in _update_indexes
    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 916, in ensure_index
    return self.create_index(key_or_list, cache_for, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 823, in create_index
    **self._get_wc_override())
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 357, in insert
    continue_on_error, self.__uuid_subtype), safe)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 861, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], details["code"])
DuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_category.$id_1_repo_id_1  dup key: { : null, : "esi-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_5_Server_RPMs_i386_5Server" }
Exception updating unit key for type [package_environment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 119, in update_database
    _update_unit_key(type_def)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 321, in _update_unit_key
    _update_indexes(type_def, True)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 312, in _update_indexes
    index_name = collection.ensure_index(mongo_index, unique=unique, drop_dups=False)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 916, in ensure_index
    return self.create_index(key_or_list, cache_for, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/connection.py", line 167, in retry
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 823, in create_index
    **self._get_wc_override())
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 357, in insert
    continue_on_error, self.__uuid_subtype), safe)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 861, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], details["code"])
DuplicateKeyError: E11000 duplicate key error index: pulp_database.units_package_environment.$id_1_repo_id_1  dup key: { : null, : "esi-Red_Hat_Enterprise_Linux_Server-Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_3" }
UpdateFailed [erratum, package_group, package_category, package_environment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulp/server/db/manage.py", line 125, in main
    return _auto_manage_db(options)
  File "/usr/lib/python2.7/site-packages/pulp/server/db/manage.py", line 150, in _auto_manage_db
    old_content_types = load_content_types(dry_run=options.dry_run)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py", line 417, in load_content_types
    _load_type_definitions(descriptors)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py", line 484, in _load_type_definitions
    database.update_database(definitions)
  File "/usr/lib/python2.7/site-packages/pulp/plugins/types/database.py", line 133, in update_database
    raise UpdateFailed(error_defs)
UpdateFailed: UpdateFailed [erratum, package_group, package_category, package_environment]
	to retry, use: --limit @/home/jenkins/workspace/satellite6_db_upgrade_migrate@2/satellite-clone/satellite-clone-playbook.retry
```

**Comment by sghai** [comment]
issue appears w/ es db and w/ 1.1.0.rc1

**Comment by sghai** [comment]
Same issue I see w/ 1.1.0. Any pointers ?

**Comment by sghai** [comment]
Facing this issue w/ 6.2 builds.. and relevant issue I see w/ pulp is:  https://pulp.plan.io/issues/1738

**Comment by sghai** [comment]
Same issue w/ 1.1.1 release.

**Comment by sghai** [comment]
Facing this issue again w/ latest build of 6.2 and release 1.1.1 on rhel7 w/o pulp data

**Comment by johnpmitsch** [comment]
@sghai can you privately send me the backup you used for this?

**Comment by sghai** [comment]
@johnpmitsch :  its because of missing answer file check in db. Since asnwer file was missing in backup and  db was from 6.2 so clone installs 6.1 and restores the db of 6.2.

**Comment by johnpmitsch** [comment]
@sghai is it safe to close this issue then?

**Comment by sghai** [comment]
Yeah.. please.
