### ISSUE TITLE
AttributeError: 'CallbackModule' object has no attribute 'set_options'

### ISSUE THREAD

**Issue by pipopopo** [RedHatSatellite/satellite-clone#238]
When running the playbook with ansible 2.4.0.0 the following error occurs:
~~~
# ansible-playbook satellite-clone-playbook.yml -vvv
~~~
~~~
ansible-playbook 2.4.0.0
  config file = /root/clone/satellite-clone/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /root/clone/satellite-clone/ansible.cfg as config file
Parsed /root/clone/satellite-clone/inventory inventory source with ini plugin
Read vars_file 'satellite-clone-vars.yml'
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/pre_install_check.yml
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/backup_check.yml
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/restore.yml
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/restore_psql_dump.yml
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/restore_mongo_dump.yml
Read vars_file 'satellite-clone-vars.yml'
statically imported: /root/clone/satellite-clone/roles/satellite-clone/tasks/reset_pulp_data.yml
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
	exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
	results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 90, in run
	self._tqm.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
	callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
AttributeError: 'CallbackModule' object has no attribute 'set_options'
~~~

Was able to fix it by downgrading the ansible version:
~~~
# yum downgrade ansible -y
# ansible --version
~~~
~~~
ansible 2.3.2.0
  config file = /root/clone/satellite-clone/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
~~~

**Comment by pondrejk** [comment]
Related https://github.com/ansible/ansible/issues/30597

**Comment by johnpmitsch** [comment]
This was fixed by https://github.com/RedHatSatellite/satellite-clone/pull/237 and is in 1.1.4
