### ISSUE TITLE
Rhel 6 - Satellite 6.2 failing

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#45]
The satellite installer fails with cert issues:
```[ERROR 2017-01-12 22:19:47 main]  qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable returned 1 instead of one of [0]
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/errors.rb:106:in `fail'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/type/exec.rb:160:in `sync'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:204:in `sync'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:89:in `perform_changes'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:88:in `each'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:88:in `perform_changes'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:20:in `evaluate'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:204:in `apply'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:217:in `eval_resource'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `call'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:335:in `thinmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:334:in `thinmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:118:in `traverse'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:138:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/puppet/parser/functions/add_progress.rb:25:in `evaluate'
                                                                                        [ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:169:in `apply'
                                                                                                                                                                     [ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/kafo/puppet/report_wrapper.rb:30:in `send'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/kafo/puppet/report_wrapper.rb:30:in `method_missing'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:168:in `apply'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:120:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:119:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:227:in `run_internal'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:134:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet.rb:246:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:133:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:302:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:236:in `main'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet.rb:246:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:198:in `main'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:159:in `run_command'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:507:in `plugin_hook'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:496:in `exit_on_fail'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:146:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:92:in `execute'
[ INFO 2017-01-12 22:19:47 main] /usr/bin/puppet:8

[ERROR 2017-01-12 22:19:47 main]  /Stage[main]/Certs::Candlepin/Exec[create candlepin qpid exchange]/returns: change from notrun to 0 failed: qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable returned 1 instead of one of [0]
[ INFO 2017-01-12 22:19:47 main]  RESOURCE Exec[create candlepin qpid exchange]
[DEBUG 2017-01-12 22:19:47 main]  Exec[create candlepin qpid exchange](provider=posix): Executing check 'qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' exchanges event'
[DEBUG 2017-01-12 22:19:47 main]  Executing 'qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' exchanges event'
[DEBUG 2017-01-12 22:19:47 main]  /Stage[main]/Certs::Candlepin/Exec[create candlepin qpid exchange]/unless: Failed: ConnectError: [Errno 1] _ssl.c:492: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
[DEBUG 2017-01-12 22:19:47 main]  Exec[create candlepin qpid exchange](provider=posix): Executing 'qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable'
[DEBUG 2017-01-12 22:19:47 main]  Executing 'qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable'
[ WARN 2017-01-12 22:19:47 main]  /Stage[main]/Certs::Candlepin/Exec[create candlepin qpid exchange]/returns: Failed: ConnectError: [Errno 1] _ssl.c:492: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
[ERROR 2017-01-12 22:19:47 main]  /Stage[main]/Certs::Candlepin/Exec[create candlepin qpid exchange]: Failed to call refresh: qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable returned 1 instead of one of [0]
[ERROR 2017-01-12 22:19:47 main]  /Stage[main]/Certs::Candlepin/Exec[create candlepin qpid exchange]: qpid-config --ssl-certificate /etc/pki/katello/certs/java-client.crt --ssl-key /etc/pki/katello/private/java-client.key -b 'amqps://sat-snap-rhel6.example.com:5671' add exchange topic event --durable returned 1 instead of one of [0]
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/errors.rb:106:in `fail'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/type/exec.rb:160:in `sync'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/type/exec.rb:583:in `refresh'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:101:in `send'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:101:in `process_callback'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:20:in `process_events'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:93:in `queued_events'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:92:in `each'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:92:in `queued_events'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/event_manager.rb:19:in `process_events'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:221:in `eval_resource'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `call'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:335:in `thinmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:334:in `thinmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:118:in `traverse'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:138:in `evaluate_without_trigger'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/puppet/parser/functions/add_progress.rb:25:in `evaluate'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:169:in `apply'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/kafo/puppet/report_wrapper.rb:30:in `send'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/gems/1.8/gems/kafo-0.7.6/modules/kafo_configure/lib/kafo/puppet/report_wrapper.rb:30:in `method_missing'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:168:in `apply'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:120:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:119:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:227:in `run_internal'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:134:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet.rb:246:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:133:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:302:in `apply_catalog'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:236:in `main'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet.rb:246:in `override'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:198:in `main'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:159:in `run_command'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:507:in `plugin_hook'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:496:in `exit_on_fail'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:146:in `run'
[ INFO 2017-01-12 22:19:47 main] /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:92:in `execute'
[ INFO 2017-01-12 22:19:47 main] /usr/bin/puppet:8```

**Comment by johnpmitsch** [comment]
This was due to my environment, closing
