### ISSUE TITLE
satellite-clone-playbook fails if /etc/katello-installer isn't present.

### ISSUE THREAD

**Issue by sideangleside** [RedHatSatellite/satellite-clone#72]
When running the `satellite-clone-playbook`, it will fail during the **run satellite 6.2 installer** step if the `/etc/katello-installer`directory is not present. 

In my setup, I was using a Satellite 6.2.6 system on RHEL 7.3 that had previously been upgraded from 6.1. 

~~~
    fatal: [172.17.0.148]: FAILED! => {"changed": true, "cmd": ["satellite-installer", "--scenario", "satellite", "--foreman-proxy-dns", "false", "--foreman-proxy-dhcp", "false"], "delta": "0:00:02.315903", "end": "2017-01-24 12:57:59.621913", "failed": true, "rc": 1, "start": "2017-01-24 12:57:57.306010", "stderr": "/usr/share/ruby/tmpdir.rb:85:in `mkdir': No such file or directory - /etc/katello-installer/d20170124-14608-1e040k0 (Errno::ENOENT)\n\tfrom /usr/share/ruby/tmpdir.rb:85:in `block in mktmpdir'\n\tfrom /usr/share/ruby/tmpdir.rb:142:in `create'\n\tfrom /usr/share/ruby/tmpdir.rb:85:in `mktmpdir'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/configuration.rb:139:in `params_default_values'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/configuration.rb:194:in `block in preset_defaults_from_puppet'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/configuration.rb:193:in `each'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/configuration.rb:193:in `preset_defaults_from_puppet'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/kafo_configure.rb:253:in `set_parameters'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/kafo_configure.rb:96:in `initialize'\n\tfrom /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `new'\n\tfrom /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'\n\tfrom /usr/share/gems/gems/kafo-0.7.6/lib/kafo/kafo_configure.rb:150:in `run'\n\tfrom /usr/sbin/satellite-installer:12:in `<main>'", "stdout": "", "stdout_lines": [], "warnings": []}
            to retry, use: --limit @/root/satellite-clone/satellite-clone-playbook.retry


~~~

**Note**: creating the `/etc/katello-installer/` directory manually and rerunning the playbook allowed it to proceed.

**Comment by sthirugn** [comment]
ACK I was able to reproduce this.

Due to some reason, this doesnt happen on straight 6.1 or straight 6.2 clones.  This happens only on cloning a satellite which was upgraded from 6.1 to 6.2 which I assume most of the customers's scenario.  Added the fix in https://github.com/RedHatSatellite/satellite-clone/pull/87.
