### ISSUE TITLE
Katello::reindex is now katello::reimport in 6.2

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#91]
We will have to handle this in our playbook. This change happened as of 6.2.7

```
TASK [sat6repro : Reset katello index - Note that this might take hours] *******
fatal: [10.8.0.148]: FAILED! => {"changed": true, "cmd": ["foreman-rake", "katello:reindex", "--trace"], "delta": "0:00:01.901796", "end": "2017-01-27 16:12:57.837519", "failed": true, "rc": 1, "start": "2017-01-27 16:12:55.935723", "stderr": "rake aborted!\nDon't know how to build task 'katello:reindex'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'\n/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'\n/opt/rh/rh-ruby22/root/usr/bin/rake:33:in `<main>'", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by sghai** [comment]
Faced similar issue:
```console
TASK [sat6repro : Reset katello index - Note that this might take hours] *******
fatal: [Server]: FAILED! => {"changed": true, "cmd": ["foreman-rake", "katello:reindex", "--trace"], "delta": "0:00:04.177142", "end": "2017-01-30 02:32:34.615848", "failed": true, "rc": 1, "start": "2017-01-30 02:32:30.438706", "stderr": "rake aborted!\nDon't know how to build task 
```
